sudo: required
language: ruby
rvm:
- 2.7.1
cache: bundler
services:
- postgresql
- docker
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle install
script:
- docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .
after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
- docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:latest
- docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $DOCKER_REPO
env:
  global:
  - secure: ovCYOnPxi0Eo3+1eTSQ7ymiJ7Lx9BkXCVud8YrDJ7IWWxm9bOuoMvUeJu2iCyfV3xxf1tZFcDF++LoAGL/1lPM1ClnlBPnNKnc9AiKEZloG/shT5tgjoFZgo34Y3FfPnL4tJ3eXCwKhD8NwYYMYTFLXNZASI1j5KbJi+Qea8fW/uD7TrCpKHPegHw2yteZaCoAX+x0CcZ4kwekqLVJLyyof5fnk52LsLWwFOokoiliZ5RUOs3vu07ywwRd5NqnAky+p87RlPTfGHvEVPqqBS185kVqGvBPg3YmGFltjbp2sRkCZqLChlELCHnwxsXW3A5xt+0lUlcWpKxJPCKj5A4pNiHAqlTNjPzA364AZ9VEcDJMLVtyDlSlBOuLuOReRjQsxl3VwMGZGR8h5W5Qxg6IDGLa7Y0z30UeO5yzduC2FTTeEX5r8gTXRWrjWiA6bK6cG37AE9Kq8Fx9aTbyFVRO5UCE9BsxabLzNK+MXEZ2KjZC7AHJeIE6ceUY/vPR34mJ4tJQAwdTTAiA+KQXtda5SMVSm3jccuowORojvuRuO+aohiZr8hykjK1hPJj8EQcTSa35JVEbPQ1+GcmfbNGOIIFcWgZecB9XCMF/opDfMl5EBOWgE0fa5DDYvIIrf7MOPuWXXq/Yl5OMw5+8a+hOmC/kRkShQ3mjRkU+NFWRg=
  - secure: N2YkyhZalBZmOgfrsnO72Huw3Rm2f3FMt2cOONlnlwuUadx6XVpCoKhf+olKuOSPinGcGSrZBjNATd6GiQNKOGf0w0fA0ypVMmV4wV66urL9Dh/2RLp3Vkqjuno3OyfVdFsE9WnZj+vGbf3ZzxBTwZlPHe0M73bRP0NE6b1NkHKgdm+AZwxMxJucdUOuPepzBPCkcTXGNgTyJ/09xonF2lRK1EtEvpU/SEsXIyKT0wpNgr2mvLnWcvkvQCo+nYDgh6t2pYm97oHeIZ/fcXlVpIFyxkZozU/+LT9YuCVVd133bmkPlHTJGffAYuHiYUIcS0vpKjELkANBOWZIZto9b/IMQPrK5wvOPUeZmt5MKrzJKURHNii69wz6WibzAASrNbDa+oeJB3y//+U518Yemts6TuULabNx9zz+rCUeLJKRdCFOWDqc8dAMCdBBrMCrYgzKWAJMToaPbxQFqyGiKI4Mdmn9mKcta9RTh9sQ9UYZq+at5sxh4kfcpgVNmegbVEEYwer/BGiuNAXns1IZ6j85yWrCUL1OOYNHdVSvNsVEiCy09S59xAnhKY0cZrfa4OvWyCg5LC+PYEmdY3l7EdSYIokUyA52dB9D8Ua2eCqTtD587xBsOzoreJL+hrkSwcJZ5laxvRjoIVE8w91i8pnqWQPQIjmWD6WsdKi+gwU=
  - secure: ndhxeY2XzC84fCcdI0YA1NnYdAZ30FCyFkuJ2ZIixJGbolRHWB7m5xuoi0k/KVsewfN7/aEDsYnV6mxXyzoSkx4QClg0tph4+pq0MFeDuFsq3CRU+XPuEDXjxRhO57hQl/1kQNIhp+QXogDXEDqturRrp846NNm2UCUySEw0JqM1luwJprh+qzCfyuR2ZrZTLUORXAOJeZkezumNcMVHhSnhs7VscNdE7cwvxMvZvXgdeCTgUGqu+wKbm/F44Y/1y7cvtjvBtjqoTIJAhwvq3kXCMClIDbzyoGLora7APMTNP+jqcowTRQ60gxnpU+EjDRX01D42HWUPpUp2pawGenKDjrFXtr84L22V0NyaMyD6F8tQDDkS3hGTyjkCULkDC1euXL+L1p9jUaGC8hRUO8teniMqMSzmN/6x6hU/baQd4oe61036AiyiMdqQtGua2WoHK3DaR+w0XvcXenSeMdzoRPKhG/odZAiW/ZIBSo14w4YNED7so0cD7x75Ug3DkSK71H16fFnQkGtcl6R2bD/2LnaVEjrrcVHAjTanDbRHzLSYnXb3c3cVCUDSXrqTfNQafE86iEl2IY2Qmn+ugrlwfAdg8BL1DzzXtefzNCODzmqooBqHu2m5klj1S8oHF3nOAgH+A12jNES8SaOjASq1eSsKQFEMDfhDiNwkA8U=
