language: ruby
rvm:
- 2.7.1
cache: bundler
services:
- postgresql
- docker
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle install 
# script:
# - bundle install
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: KoPrjqEqdyl4xHzxIn8kI4bY6SD6bLeWTRnHZDTO9G3ZAOfDAPA9YWs5E+8yRv6c/Jk5Jz8vEfBd4uDmmxDNVjw6aJrM5akQP8TY056YpDRr+ES3eO/Z7D8ewV6SBiqbwMLGjI8TV+yMBKZjyRLKy68rcS48a9g8wj9FxZ41WPp81mGADM13GyXlf5vcIKhbEDyYvpQbbubvBmqzIL25faLqnoKoEGI0YUaf9MZtzLrz0dd5Y6Qomef4ZhkyhT/Qniupqd2BrtLlZzdqra3cQXByn+H1UZnly9mWCYQ/7UwiNhH+wMztucIu7NpnSS1E2P2t1TFjFsFB2QQI3m/s7T3lEvlsjUa3LSSG5OnflzxZqgVaw+CbfX+EUQcvEFB1MncFvLxE9i46j3bQA/6oUHuSgk/ePzf6DDjWpgLN0EYSeYbtLKFyG2Ghhcl4BZdOt36DHYcxqOdclcKo6aoGiArHW/+ZCj5lAtlHDfqEJFj833YbVXyf53i685e/nN9nZLSLrFf0Tks7XLYCmzO/lPYNAPpx6HV5AVoZBMQn6rjFxDV/V0OgQQOm1idF6u/4oPdSoFMN0WScRMAJzgcFtC+HYeIFBFPgNQ1AqnrC4DbBnFjtHc3U6eXAxl7kg5K8OPHt8Pws4i9wtuVCsU2swite2MHBMgf9gu/QhL8HG/Q=
  - secure: uDgSuOaQ7dS2RKVkkcO7UnGWJcPsw0cheRzlnNbrArpVqPe1609yLZ+CZ6JPcDeGGZ9pmlT1d1aO2Pf90AaNN8kh/gTjIuChEWEQnVNod9JO0tzsVI9ERY1gYRyO4aHq/10Ys2HY1TxSadlli2gWW0jOJrKNASEgUo3REx3I6sm+qOwaWlNMV/KI9ozm9g0lN3VFNxfYw8Giuds1uPyYCYlOf4SR0S/v6ETnT4VgENdfBI6IaTHiNhZBOdDCLnViLNuqXpOOI0J3GjdMUG39778jNs+r3hGgs5hEpS6RV9RIsQLUxYQDiNvUkhMgoXyf3mW9OPa7YPttvMf4ALSdMvUYgo55/JStsMEVCVI2G4gVKNviBncNx921jXfAvt3lP/nDCqCtCrnjcExj/FOsm50VLVNzECpeObsLT3iV51n3dsFKDNme8BSnwlJgr61VSWSC+Qxcny5KF3TU01+XLB1UwpdM3AHWrL0ujzsZL1CQcjYvFVbRjGZE3qBs3o2sEotEtBcgh0J7oxXL1R0eA105Rl+SZ38oqaZ2j0d1KnNEgaFapEtqxF2urvQfnLNW55+LcDKT12YNIWKJ3d51Flv/k0KAhHaaZzEtv/3NO+s+nP3vsIMi0zSGBSzRrOheewJMW3e3vhcAvVeGU6/863KWZkk8LNHhuJRs4GzbhvU=
# after_success:
# - docker login -u $DOCKER_USER -p $DOCKER_PASS docker.io
# - export REPO=iammariam/bbb_lti_broker
# - export TAG=latest
# - docker-compose build -t $REPO:$COMMIT .
# - docker tag $REPO:$COMMIT $REPO:$TAG
# - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
# - docker push $REPO
jobs:
  include:
  - stage: build
    name: build docker image
    script:
      - docker build -t $DOCKER_REPO:$TRAVIS_COMMIT .
    after_success:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
      - docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:latest
      - docker tag $DOCKER_REPO:$TRAVIS_COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_REPO